### PR TITLE
Make it work in a worker context

### PR DESCRIPTION
**Pull request by martenrichter**
I am feeding my Video- and AudioCodec from a Worker Thread, this PR should fix some exceptions, which occur during the initial loading of the polyfill.
There may be further related issues may be present, these will be addressed in later PR, while testing the components.
It would be nice, if you consider adding these changes.

### CODE REVIEW

**Comment by Yahweasel** [comment]
A couple things to fix:

1. You left a .test.js in package.json. Fix it back to .min.js
2. I don't want the polyfill to break on systems earlier than globalThis. Either add the globalthis polyfill, or polyfill it as `(globalThis || window)` yourself.

**Comment by Yahweasel** [comment]
It already breaks on workers ;) . It's fine to add that too, I'm just principally concerned with not breaking on systems where it currently works.

**Comment by martenrichter** [comment]
In order to also potentially not harm node.js I added a polyfill. (not yet tested, will do it next weekend, or test it yourself).
But also changes in libav.js are required for workers, it is buried in the last changes in the closed issue.

**Comment by martenrichter** [comment]
After getting the correct polyfill. This is now tested to be correctly loaded. At least I get the same anull error than last week. A PR for libav.js is coming soon to supply loading code in bundler context.

**Pull request merged**
