### PR TITLE
Migrate building to rollup with mjs support

### PR DESCRIPTION
**Pull request by Donil**
Hi! That is another one PR - adding support of MJS (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) bundle. 

I made this with rollup since it's really good build tool and browserify is not needed anymore since we have ES2015 modules.

So for now we have two bundles:
1. libavjs-webcodecs-polyfill.min.js - UMD bundle (the same as you have now)
2. libavjs-webcodecs-polyfill.min.mjs - MJS bundle that is friendly for codebases that need to distribute as mjs

Take a look on it and say if you are interested with that way

### CODE REVIEW

**Comment by Yahweasel** [comment]
Y'know what everybody loves?

People being opinionated about build systems.

**Comment by Yahweasel** [comment]
I believe the answer for .mjs is esmify. Not sure what the answer is for .d.ts, but I'm sure tsify does it.

**Comment by Donil** [comment]
Yes, generating d.ts files is not problem with browserfy, but generating .mjs file is not possible I think.
esmify transfrorm **from** "import / export" to browserify but not **to** bundle with "import/export". Correct me if I'm wrong

**Comment by Donil** [comment]
It seems I've found the reason on why I can not use current UMD bundle with my case - I'm working on JS library and want to build it into the signle JS file (as you library does). For that I have to embed libavjs-webcodecs-polyfill into my bundle.
But since polyfill is standalone UMD module it has this code:
```
if (typeof exports === "object" && typeof module !== "undefined") {
  module.exports = f();
}
```
So it just overrides my ESM module exports and breaks it. 
I resolved it with https://www.npmjs.com/package/@rollup/plugin-commonjs for my case so I'm closing this PR and will return with new PR soon - to add d.ts files generation :)

**Pull request closed without merging**
